server:
  port: 8772
  
spring:
  application:
    name: msa-weather-data-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true