#server:
#  port: 8773
  
spring:
  application:
    name: msa-weather-city-eureka
 # cloud:
  #  config:
  #    profile: dev
 #     uri: http://localhost:8776/
  rabbitmq:
    host: localhost
    port: 5672
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true