server:
  port: 8762
spring:
  application:
    #name: micro-weather-eureka-server-standby
    name: micro-weather-eureka-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    #心跳时间，Eureka server和client之间每隔30秒会进行一次心跳通信
    lease-renewal-interval-in-seconds: 30 
  server:
    enableSelfPreservation: false