
server:
  port: 8774
  
spring:
  application:
    name: msa-weather-report-eureka-feign-gateway-hystrix
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
ribbon:
  eureka:
    enable: true
