server:
  port: 8771
  
spring:
  application:
    name: msa-weather-collection-eureka-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
   config:
     feignName:
       connectTimeout: 5000
       readTimeout: 5000